### PR TITLE
Add fallback autoloader for standalone bundle testing

### PR DESCRIPTION
**Pull request by jsor**
The default autoload configuration in Tests/bootstrap.php does not load properly since UniversalClassLoader always generate the path from the class name.

Not sure if this is the nicest workaround, but it works if you want to run phpunit from a direct git clone.

### CODE REVIEW

**Comment by henrikbjorn** [comment]
As this bundle cannot be used without symfony i think this isnt necesarry. Also it wouldnt work because it would fail to create an instance of the normal Symfony ClassLoader.

**Comment by jsor** [comment]
When fixing things for PR's i usually do this from separate clones. So, the ability to run phpunit not being inside a Symfony project would be handy for me. But i'm fine not having this PR merged, feel free to close it :)

**Comment by henrikbjorn** [comment]
Wel the problem is it wont work because you will get a class not found error in this file if trying to do it outside. There is a way to configure the symfony path instead which you should use (dont have permissions to close it)

**Comment by jsor** [comment]
This is **not** a replacement of the `UniversalClassLoader` just an addition to load the `SimpleThings\FormExtraBundle` classes if you run phpunit from within a separate clone (not within a Symfony project). Since the classes are not in `/path/to/SimpleThings/FormExtraBundle` but in something like `/path/to/SimpleThingsFormExtraBundle` the `UniversalClassLoader` is not usable here. The path to Symfony is still configured through phpunit.xml.

**Comment by henrikbjorn** [comment]
yes but it will still run the bootstrap file and be unable to load the class and therefor you will get an error. This will not work at all.

**Comment by jsor** [comment]
Hmm...i don't get what you mean. Loading the Symfony classes has nothing to do with my code.They will be loaded in both cases through the `UniversalClassLoader`. My code is only for loading the bundle classes.

**Comment by henrikbjorn** [comment]
`'SimpleThings\\FormExtraBundle' => '../../',` this line says the bundle namespace should be loaded from two directories back from the current file which is the root folder of the bundle, then why would you need to change anything ?

**Comment by jsor** [comment]
Because the `UniversalClassLoader` will generate a path like `../../SimpleThings/FormExtraBundle/Foo/Bar.php` which is only correct if you have installed it as a bundle in a Symfony project. For a standlaone clone you need something like `./Foo/Bar.php`.

**Comment by jsor** [comment]
I'm using `git clone git://github.com/jsor/SimpleThingsFormExtraBundle.git SimpleThings/FormExtraBundle` now.

**Pull request closed without merging**
