### PR TITLE
property_path deprecated at false

### PR DESCRIPTION
**Pull request by RomainLegouverneur**
Since 2.1, the mapped option has been added for this use-case. (http://symfony.com/doc/2.3/reference/forms/types/form.html#property-path)

### CODE REVIEW

**Comment by stof** [comment]
:+1: Supporting 2.3 is more important than supporting 2.0

**Comment by DavidBadura** [comment]
How should I do that? Should I crate a new tag for the 2.0 version?

**Comment by stof** [comment]
@DavidBadura actually, I think the 2.0 was already dropped in the bundle by some previous changes (but not sure)

**Comment by DavidBadura** [comment]
that's true

**Pull request merged**
