### PR TITLE
remove http (on form view) to auto call https on secure pages

### PR DESCRIPTION
**Pull request by Bilbous**

### CODE REVIEW

**Comment by henrikbjorn** [comment]
Does this work? I thought the used `secure` as the prefix for their apis

**Comment by Bilbous** [comment]
It's works for me. All my scripts are loaded like this to avoid security "violation" on browsers.
The RFC 3986 section 5.2 explain it :

If the scheme component is defined, indicating that the reference starts with a scheme name, then the reference is interpreted as an absolute URI and we are done. Otherwise, the reference URI's scheme is inherited from the base URI's scheme component.

**Comment by stof** [comment]
@henrikbjorn Gravatar is using a different subdomain, not Google.

**Comment by henrikbjorn** [comment]
@beberlei  this is valid :)

**Pull request merged**
