### PR TITLE
Make (recaptcha) config optional

### PR DESCRIPTION
**Pull request by jsor**
I do not want to use the `RecaptchaType`. This PR makes the whole `simple_things_form_extra` configuration optional.

Not sure if the `SimpleThings\FormExtraBundle\Service\Recaptcha` and `SimpleThings\FormExtraBundle\Form\Type\RecaptchaType`should now throw an exception if public/private keys are empty.

### CODE REVIEW

**Comment by stof** [comment]
This should be done in a different way IMO: registering the recaptcha type only when you configure it (and making the subnodes mandatory when you enable recaptcha)

**Comment by jsor** [comment]
Good point. 

Can't think of a use case atm, but could someone want to have the type registered without being forced to configure the key in the config? Maybe @beberlei can decide how to handle this :)

**Comment by stof** [comment]
The recaptcha type is not usable without its config as you will be unable to validate it.

**Comment by beberlei** [comment]
The type should throw an exception in buildForm() if no key isset and then making the configuration optional works.

**Comment by stof** [comment]
@beberlei I agree that it works, but it seems unclean to register a service in a broken state. The following would allow making it in a cleaner way (with a small:

``` php

<?php
//...
        if (isset($config['recaptcha'])) {
            $loader->load('recaptcha.xml');
            $container->getDefinition('simple_things_form_extra.service.recaptcha')->replaceArgument(1, $config['recaptcha']['private_key']);
            $container->getDefinition('simple_things_form_extra.form.type.recaptcha')->replaceArgument(1, $config['recaptcha']['public_key']);
        }

```

Btw, are the default empty values (used only when the recaptcha node is set in the current Configuration class) really a good idea ? I don't think the recaptcha service works without them. You should maybe make this 2 node required (without making the parent node required so that they are required only when recaptcha is set).

**Comment by jsor** [comment]
I've send another PR based on the suggestions by @stof: #14

**Pull request merged**
