### PR TITLE
Removed useless form extension

### PR DESCRIPTION
**Pull request by stof**
The attr option has been added in Symfony itself before the 2.0.0 release.

### CODE REVIEW

**Comment by henrikbjorn** [comment]
You are right, when was it ported to core?

:+1:

**Comment by stof** [comment]
during one of the beta or RC releases. I don't remember which one. I simply checked that 2.0.0 already have it

**Comment by stof** [comment]
@beberlei ping

**Comment by quba** [comment]
Merge please.

**Comment by henrikbjorn** [comment]
@quba does it provide a problem for you ?

**Pull request merged**
